/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as TradingPsychologyRouteImport } from './routes/trading-psychology';
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml';
import { Route as SearchRouteImport } from './routes/search';
import { Route as RiskManagementRouteImport } from './routes/risk-management';
import { Route as LearnRouteImport } from './routes/learn';
import { Route as IndicatorsRouteImport } from './routes/indicators';
import { Route as FinanceBasicsRouteImport } from './routes/finance-basics';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as ChartPatternsRouteImport } from './routes/chart-patterns';
import { Route as CandlestickPatternsRouteImport } from './routes/candlestick-patterns';
import { Route as CalculatorsRouteImport } from './routes/calculators';
import { Route as BlogRouteImport } from './routes/blog';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ArticleSlugRouteImport } from './routes/article.$slug';

const TradingPsychologyRoute = TradingPsychologyRouteImport.update({
  id: '/trading-psychology',
  path: '/trading-psychology',
  getParentRoute: () => rootRouteImport
});
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport
});
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport
});
const RiskManagementRoute = RiskManagementRouteImport.update({
  id: '/risk-management',
  path: '/risk-management',
  getParentRoute: () => rootRouteImport
});
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport
});
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport
});
const FinanceBasicsRoute = FinanceBasicsRouteImport.update({
  id: '/finance-basics',
  path: '/finance-basics',
  getParentRoute: () => rootRouteImport
});
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport
});
const ChartPatternsRoute = ChartPatternsRouteImport.update({
  id: '/chart-patterns',
  path: '/chart-patterns',
  getParentRoute: () => rootRouteImport
});
const CandlestickPatternsRoute = CandlestickPatternsRouteImport.update({
  id: '/candlestick-patterns',
  path: '/candlestick-patterns',
  getParentRoute: () => rootRouteImport
});
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport
});
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport
});
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport
});
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
});
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport
});











































































































































































































































const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CalculatorsRoute: CalculatorsRoute,
  CandlestickPatternsRoute: CandlestickPatternsRoute,
  ChartPatternsRoute: ChartPatternsRoute,
  ContactRoute: ContactRoute,
  FinanceBasicsRoute: FinanceBasicsRoute,
  IndicatorsRoute: IndicatorsRoute,
  LearnRoute: LearnRoute,
  RiskManagementRoute: RiskManagementRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradingPsychologyRoute: TradingPsychologyRoute,
  ArticleSlugRoute: ArticleSlugRoute
};
export const routeTree = rootRouteImport.
_addFileChildren(rootRouteChildren).
_addFileTypes();