/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingPsychologyRouteImport } from './routes/trading-psychology'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RiskManagementRouteImport } from './routes/risk-management'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as FinanceBasicsRouteImport } from './routes/finance-basics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChartPatternsRouteImport } from './routes/chart-patterns'
import { Route as CandlestickPatternsRouteImport } from './routes/candlestick-patterns'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'

const TradingPsychologyRoute = TradingPsychologyRouteImport.update({
  id: '/trading-psychology',
  path: '/trading-psychology',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskManagementRoute = RiskManagementRouteImport.update({
  id: '/risk-management',
  path: '/risk-management',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBasicsRoute = FinanceBasicsRouteImport.update({
  id: '/finance-basics',
  path: '/finance-basics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartPatternsRoute = ChartPatternsRouteImport.update({
  id: '/chart-patterns',
  path: '/chart-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const CandlestickPatternsRoute = CandlestickPatternsRouteImport.update({
  id: '/candlestick-patterns',
  path: '/candlestick-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calculators': typeof CalculatorsRoute
  '/candlestick-patterns': typeof CandlestickPatternsRoute
  '/chart-patterns': typeof ChartPatternsRoute
  '/contact': typeof ContactRoute
  '/finance-basics': typeof FinanceBasicsRoute
  '/indicators': typeof IndicatorsRoute
  '/learn': typeof LearnRoute
  '/risk-management': typeof RiskManagementRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading-psychology': typeof TradingPsychologyRoute
  '/article/$slug': typeof ArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calculators': typeof CalculatorsRoute
  '/candlestick-patterns': typeof CandlestickPatternsRoute
  '/chart-patterns': typeof ChartPatternsRoute
  '/contact': typeof ContactRoute
  '/finance-basics': typeof FinanceBasicsRoute
  '/indicators': typeof IndicatorsRoute
  '/learn': typeof LearnRoute
  '/risk-management': typeof RiskManagementRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading-psychology': typeof TradingPsychologyRoute
  '/article/$slug': typeof ArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calculators': typeof CalculatorsRoute
  '/candlestick-patterns': typeof CandlestickPatternsRoute
  '/chart-patterns': typeof ChartPatternsRoute
  '/contact': typeof ContactRoute
  '/finance-basics': typeof FinanceBasicsRoute
  '/indicators': typeof IndicatorsRoute
  '/learn': typeof LearnRoute
  '/risk-management': typeof RiskManagementRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading-psychology': typeof TradingPsychologyRoute
  '/article/$slug': typeof ArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/calculators'
    | '/candlestick-patterns'
    | '/chart-patterns'
    | '/contact'
    | '/finance-basics'
    | '/indicators'
    | '/learn'
    | '/risk-management'
    | '/search'
    | '/sitemap.xml'
    | '/trading-psychology'
    | '/article/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/calculators'
    | '/candlestick-patterns'
    | '/chart-patterns'
    | '/contact'
    | '/finance-basics'
    | '/indicators'
    | '/learn'
    | '/risk-management'
    | '/search'
    | '/sitemap.xml'
    | '/trading-psychology'
    | '/article/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/calculators'
    | '/candlestick-patterns'
    | '/chart-patterns'
    | '/contact'
    | '/finance-basics'
    | '/indicators'
    | '/learn'
    | '/risk-management'
    | '/search'
    | '/sitemap.xml'
    | '/trading-psychology'
    | '/article/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CandlestickPatternsRoute: typeof CandlestickPatternsRoute
  ChartPatternsRoute: typeof ChartPatternsRoute
  ContactRoute: typeof ContactRoute
  FinanceBasicsRoute: typeof FinanceBasicsRoute
  IndicatorsRoute: typeof IndicatorsRoute
  LearnRoute: typeof LearnRoute
  RiskManagementRoute: typeof RiskManagementRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradingPsychologyRoute: typeof TradingPsychologyRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading-psychology': {
      id: '/trading-psychology'
      path: '/trading-psychology'
      fullPath: '/trading-psychology'
      preLoaderRoute: typeof TradingPsychologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-management': {
      id: '/risk-management'
      path: '/risk-management'
      fullPath: '/risk-management'
      preLoaderRoute: typeof RiskManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-basics': {
      id: '/finance-basics'
      path: '/finance-basics'
      fullPath: '/finance-basics'
      preLoaderRoute: typeof FinanceBasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-patterns': {
      id: '/chart-patterns'
      path: '/chart-patterns'
      fullPath: '/chart-patterns'
      preLoaderRoute: typeof ChartPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candlestick-patterns': {
      id: '/candlestick-patterns'
      path: '/candlestick-patterns'
      fullPath: '/candlestick-patterns'
      preLoaderRoute: typeof CandlestickPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CalculatorsRoute: CalculatorsRoute,
  CandlestickPatternsRoute: CandlestickPatternsRoute,
  ChartPatternsRoute: ChartPatternsRoute,
  ContactRoute: ContactRoute,
  FinanceBasicsRoute: FinanceBasicsRoute,
  IndicatorsRoute: IndicatorsRoute,
  LearnRoute: LearnRoute,
  RiskManagementRoute: RiskManagementRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradingPsychologyRoute: TradingPsychologyRoute,
  ArticleSlugRoute: ArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
